config/routes.rb
Rails.application.routes.draw do
  resources :autostatincomes, only: :index
  resources :statincomes, only: :index
  resources :autostats, only: :index
  resources :etats
  resources :autoincomes
  resources :dashauto
  resources :autoexpenses
  resources :fonds
  resources :depenses
  resources :automobiles
  devise_for :administrateurs
  resources :accueil
  resources :incategories
  resources :incomes
  resources :sources
  resources :categories
  root to: 'accueil#index'
  resources :expenses
  resources :statistics, only: :index
   devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrateur.rb
class Administrateur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  	has_many :expenses
  	has_many :autoexpenses
  	has_many :autoincomes
	has_many :incomes
	has_many :automobiles
	has_many :depenses
end

app/models/autoexpense.rb
class Autoexpense < ApplicationRecord
		default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/autoincome.rb
class Autoincome < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/automobile.rb
class Automobile < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:prix)
  end
  belongs_to :administrateur
  belongs_to :etat
  has_many :depenses
  has_many :autoexpenses
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :expenses
end

app/models/depense.rb
class Depense < ApplicationRecord
  belongs_to :administrateur
  belongs_to :automobile
end

app/models/etat.rb
class Etat < ApplicationRecord
	has_many :automobiles
end

app/models/expense.rb
class Expense < ApplicationRecord
  default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
  belongs_to :category
  belongs_to :source
  belongs_to :administrateur
end

app/models/fond.rb
class Fond < ApplicationRecord
end

app/models/incategory.rb
class Incategory < ApplicationRecord
	has_many :expenses
end

app/models/income.rb
class Income < ApplicationRecord
	default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	  belongs_to :incategory
  	  belongs_to :source
  	  belongs_to :administrateur
end

app/models/source.rb
class Source < ApplicationRecord
	has_many :expenses
	has_many :incomes
end

app/controllers/dashauto_controller.rb
class DashautoController < ApplicationController
  def index
  	@fonds = Fond.all
  	@autoexpenses = Autoexpense.all
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/autostats_helper.rb
module AutostatsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashauto_helper.rb
module DashautoHelper
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/helpers/etats_helper.rb
module EtatsHelper
end

app/helpers/fonds_helper.rb
module FondsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/dashauto/index.html.erb
<%=render 'menus/top'%>
<div id="layoutSidenav">
<%=render 'menus/side'%>
  <div id="layoutSidenav_content">
    <main>
    	<div class="container-fluid">
            <h1 class="mt-4">Tableau de bord</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Tableau de bord</li>
            </ol>
            <p id="notice" class="text-success"><%= notice %></p>
            <div class="row">
            	<div class="col-lg-4">
            		<div class="row">
                          <div class="col-lg-12 col-12">
                          	 <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">
                                    	<h2>Fond disponible</h2>

<div>
  
  <% @fonds.each do |fond| %>
        <h4>Total de dépenses du mois: <b><%= fond.montant - Autoexpense.total_for_current_month + Autoincome.total_for_current_month %> XFA</b>.</h4>
    <% end %>
</div>

                                    </div>
                                    <div class="card-footer d-none align-items-center justify-content-between">
                                        <%= link_to "Bilan de dépenses", statistics_path, class:"small text-white stretched-link" %>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
    
</div>
                        </div>
            	</div>
            	<div class="col-lg-4">
            		<div class="row">
                          <div class="col-lg-12 col-12">
                          	 <div class="card bg-success text-white mb-4">
                                    <div class="card-body">
                                    	<h2>Entrées</h2>

<div>
  
  <% @fonds.each do |fond| %>
        <h4>Total des entrées du mois: <b><%= Autoincome.total_for_current_month %> XFA</b>.</h4>
    <% end %>
</div>

                                    </div>
                                    <div class="card-footer align-items-center justify-content-between">
                                        <%= link_to "Bilan des entrées", autostatincomes_path, class:"small text-white stretched-link" %>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
    
</div>
                        </div>
            	</div>
            	<div class="col-lg-4">
            		<div class="row">
                          <div class="col-lg-12 col-12">
                            <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">
                                    	<h2>Dépenses</h2>

<div>
  <h4>Total des dépenses du mois: <b><%= Autoexpense.total_for_current_month %> XFA</b>.</h4>
</div>

                                    </div>
                                    <div class="card-footer align-items-center justify-content-between">
                                        <%= link_to "Bilan des dépenses", autostats_path, class:"small text-white stretched-link" %>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>

<%= link_to 'Ajouter une entrée', new_autoexpense_path, class:"btn btn-danger mt-2" %>
<div class="table-responsive">
  <table class="table table-bordered mt-2" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Price</th>
      <th>Description</th>
      <th>Travaux</th>
      <th>Designation</th>
      <th>Billed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @autoexpenses.each do |autoexpense| %>
      <tr>
        <td><%= autoexpense.price %></td>
        <td><%= autoexpense.description %></td>
        <td><%= autoexpense.travaux %></td>
        <td><%= autoexpense.designation %></td>
        <td><%= autoexpense.billed_at %></td>
        <td><%= link_to 'Show', autoexpense %></td>
        <td><%= link_to 'Edit', edit_autoexpense_path(autoexpense) %></td>
        <td><%= link_to 'Destroy', autoexpense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
                          </div>
                        </div>
            	</div>
            </div>
        </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; <b>OW Technology</b> 2020</div>
                         
                        </div>
                    </div>
                </footer>
   </div>
</div>