config/routes.rb
Rails.application.routes.draw do
  resources :autostatincomes, only: :index
  resources :statincomes, only: :index
  resources :autostats, only: :index
  resources :etats
  resources :autoincomes
  resources :dashauto
  resources :autoexpenses
  resources :fonds
  resources :depenses
  resources :automobiles
  devise_for :administrateurs
  resources :accueil
  resources :incategories
  resources :incomes
  resources :sources
  resources :categories
  root to: 'accueil#index'
  resources :expenses
  resources :statistics, only: :index
   devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrateur.rb
class Administrateur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  	has_many :expenses
  	has_many :autoexpenses
  	has_many :autoincomes
	has_many :incomes
	has_many :automobiles
	has_many :depenses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autoexpense.rb
class Autoexpense < ApplicationRecord
		default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/autoincome.rb
class Autoincome < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/automobile.rb
class Automobile < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:prix)
  end
  belongs_to :administrateur
  belongs_to :etat
  has_many :depenses
  has_many :autoexpenses
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :expenses
end

app/models/depense.rb
class Depense < ApplicationRecord
  belongs_to :administrateur
  belongs_to :automobile
end

app/models/etat.rb
class Etat < ApplicationRecord
	has_many :automobiles
end

app/models/expense.rb
class Expense < ApplicationRecord
  default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
  belongs_to :category
  belongs_to :source
  belongs_to :administrateur
end

app/models/fond.rb
class Fond < ApplicationRecord
end

app/models/incategory.rb
class Incategory < ApplicationRecord
	has_many :expenses
end

app/models/income.rb
class Income < ApplicationRecord
	default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	  belongs_to :incategory
  	  belongs_to :source
  	  belongs_to :administrateur
end

app/models/source.rb
class Source < ApplicationRecord
	has_many :expenses
	has_many :incomes
end

app/controllers/etats_controller.rb
class EtatsController < ApplicationController
  before_action :set_etat, only: [:show, :edit, :update, :destroy]

  # GET /etats
  # GET /etats.json
  def index
    @etats = Etat.all
  end

  # GET /etats/1
  # GET /etats/1.json
  def show
  end

  # GET /etats/new
  def new
    @etat = Etat.new
  end

  # GET /etats/1/edit
  def edit
  end

  # POST /etats
  # POST /etats.json
  def create
    @etat = Etat.new(etat_params)

    respond_to do |format|
      if @etat.save
        format.html { redirect_to @etat, notice: 'Etat was successfully created.' }
        format.json { render :show, status: :created, location: @etat }
      else
        format.html { render :new }
        format.json { render json: @etat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etats/1
  # PATCH/PUT /etats/1.json
  def update
    respond_to do |format|
      if @etat.update(etat_params)
        format.html { redirect_to @etat, notice: 'Etat was successfully updated.' }
        format.json { render :show, status: :ok, location: @etat }
      else
        format.html { render :edit }
        format.json { render json: @etat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etats/1
  # DELETE /etats/1.json
  def destroy
    @etat.destroy
    respond_to do |format|
      format.html { redirect_to etats_url, notice: 'Etat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etat
      @etat = Etat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def etat_params
      params.require(:etat).permit(:titre)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/autostats_helper.rb
module AutostatsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashauto_helper.rb
module DashautoHelper
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/helpers/etats_helper.rb
module EtatsHelper
end

app/helpers/fonds_helper.rb
module FondsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/etats/_form.html.erb
<%= form_with(model: etat, local: true) do |form| %>
  <% if etat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(etat.errors.count, "error") %> prohibited this etat from being saved:</h2>

      <ul>
      <% etat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/etats/edit.html.erb
<h1>Editing Etat</h1>

<%= render 'form', etat: @etat %>

<%= link_to 'Show', @etat %> |
<%= link_to 'Back', etats_path %>

app/views/etats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Etats</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @etats.each do |etat| %>
      <tr>
        <td><%= etat.titre %></td>
        <td><%= link_to 'Show', etat %></td>
        <td><%= link_to 'Edit', edit_etat_path(etat) %></td>
        <td><%= link_to 'Destroy', etat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Etat', new_etat_path %>

app/views/etats/new.html.erb
<h1>New Etat</h1>

<%= render 'form', etat: @etat %>

<%= link_to 'Back', etats_path %>

app/views/etats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @etat.titre %>
</p>

<%= link_to 'Edit', edit_etat_path(@etat) %> |
<%= link_to 'Back', etats_path %>