config/routes.rb
Rails.application.routes.draw do
  resources :autostatincomes, only: :index
  resources :statincomes, only: :index
  resources :autostats, only: :index
  resources :etats
  resources :autoincomes
  resources :dashauto
  resources :autoexpenses
  resources :fonds
  resources :depenses
  resources :automobiles
  devise_for :administrateurs
  resources :accueil
  resources :incategories
  resources :incomes
  resources :sources
  resources :categories
  root to: 'accueil#index'
  resources :expenses
  resources :statistics, only: :index
   devise_scope :administrateur do
    get '/administrateurs/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrateur.rb
class Administrateur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  	has_many :expenses
  	has_many :autoexpenses
  	has_many :autoincomes
	has_many :incomes
	has_many :automobiles
	has_many :depenses
end

app/models/autoexpense.rb
class Autoexpense < ApplicationRecord
		default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/autoincome.rb
class Autoincome < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	belongs_to :administrateur
	belongs_to :automobile
end

app/models/automobile.rb
class Automobile < ApplicationRecord
			default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:prix)
  end
  belongs_to :administrateur
  belongs_to :etat
  has_many :depenses
  has_many :autoexpenses
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :expenses
end

app/models/depense.rb
class Depense < ApplicationRecord
  belongs_to :administrateur
  belongs_to :automobile
end

app/models/etat.rb
class Etat < ApplicationRecord
	has_many :automobiles
end

app/models/expense.rb
class Expense < ApplicationRecord
  default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
  belongs_to :category
  belongs_to :source
  belongs_to :administrateur
end

app/models/fond.rb
class Fond < ApplicationRecord
end

app/models/incategory.rb
class Incategory < ApplicationRecord
	has_many :expenses
end

app/models/income.rb
class Income < ApplicationRecord
	default_scope { order(billed_at: :desc) }

  def self.total_for_current_month
    where("billed_at > ? AND billed_at < ?", Time.current.beginning_of_month, Time.current.end_of_month).sum(:price)
  end
	  belongs_to :incategory
  	  belongs_to :source
  	  belongs_to :administrateur
end

app/models/source.rb
class Source < ApplicationRecord
	has_many :expenses
	has_many :incomes
end

app/controllers/automobiles_controller.rb
class AutomobilesController < ApplicationController
  before_action :set_automobile, only: [:show, :edit, :update, :destroy, :vendre]
  before_action :authenticate_administrateur!, except:[:index, :show]
  # GET /automobiles
  # GET /automobiles.json
  def index
    @automobiles = Automobile.all
    @dispos = Automobile.all.where("etat_id= 1")
    @vendus = Automobile.all.where("etat_id= 2")
  end

  # GET /automobiles/1
  # GET /automobiles/1.json
  def show
  end

  # GET /automobiles/new
  def new
    @automobile = current_administrateur.automobiles.build
  end

  # GET /automobiles/1/edit
  def edit
  end

  # GET /automobiles/1/edit
  def vendre
  end

  # POST /automobiles
  # POST /automobiles.json
  def create
    @automobile = current_administrateur.automobiles.build(automobile_params)

    respond_to do |format|
      if @automobile.save
        format.html { redirect_to automobiles_url, notice: 'Automobile ajoutée.' }
        format.json { render :show, status: :created, location: @automobile }
      else
        format.html { render :new }
        format.json { render json: @automobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automobiles/1
  # PATCH/PUT /automobiles/1.json
  def update
    respond_to do |format|
      if @automobile.update(automobile_params)
        format.html { redirect_to automobiles_url, notice: 'Automobile modifiée.' }
        format.json { render :show, status: :ok, location: @automobile }
      else
        format.html { render :edit }
        format.json { render json: @automobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automobiles/1
  # DELETE /automobiles/1.json
  def destroy
    @automobile.destroy
    respond_to do |format|
      format.html { redirect_to automobiles_url, notice: 'Automobile supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automobile
      @automobile = Automobile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def automobile_params
      params.require(:automobile).permit(:marque, :modele, :couleur, :matricule, :prix, :administrateur_id, :billed_at, :price, :etat_id)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/automobiles_helper.rb
module AutomobilesHelper
end

app/helpers/autostats_helper.rb
module AutostatsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashauto_helper.rb
module DashautoHelper
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/helpers/etats_helper.rb
module EtatsHelper
end

app/helpers/fonds_helper.rb
module FondsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/automobiles/_form.html.erb
<%= form_with(model: automobile, local: true) do |form| %>
  <% if automobile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(automobile.errors.count, "error") %> prohibited this automobile from being saved:</h2>

      <ul>
      <% automobile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="form-group col-6">
    <%= form.label :marque %>
    <%= form.text_field :marque, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :modèle %>
    <%= form.text_field :modele, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :couleur %>
    <%= form.text_field :couleur, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :matricule %>
    <%= form.text_field :matricule, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :prix %>
    <%= form.text_field :prix, class:"form-control", required: :true %>
  </div>
  
  <div class="form-group col-6">
    <%= form.label :etat %>
    <%= form.hidden_field :etat_id, class:"form-control", required: :true, value: 1 %>
  </div>

    <div class="form-group col-6">
    <%= form.label :entrée_le %>
    <%= form.datetime_select :billed_at, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-12">
    <%= form.submit "Ajouter l'automobile", class:"btn btn-success" %>
  </div>
  </div>
<% end %>

app/views/automobiles/edit.html.erb
<h1>Editing Automobile</h1>

<%= render 'form', automobile: @automobile %>

<%= link_to 'Show', @automobile %> |
<%= link_to 'Back', automobiles_path %>

app/views/automobiles/index.html.erb
   <%=render 'menus/top'%>
        <div id="layoutSidenav">
            <%=render 'menus/side'%>
                         <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Automobiles</h1>
                        <%= link_to 'Ajouter une Automobile', new_automobile_path, class:"btn btn-success mt-2" %>
                        <div class="row">
                          <div class="col-lg-6 col-12">
<p id="notice"><%= notice %></p>
<div class="card bg-success text-white mb-4">
                                    <div class="card-body">
                                      <div>
  <h3>Automobiles disponibles: <b><%=@dispos.count%></b></h3>
</div>

                                    </div>
                                    <div class="card-footer align-items-center justify-content-between d-none">
                                      <%= link_to "Bilan", statistics_path, class:"small text-white stretched-link" %>
                                        
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>

<div class="table-responsive mt-2">
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr class="bg-dark text-white text-center">
      <th>Marque</th>
      <th>Modele</th>
      <th>Prix</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @dispos.each do |automobile| %>
      <tr>
        <td><%= automobile.marque %></td>
        <td><%= automobile.modele %></td>
        <td><%= automobile.prix.to_i %></td>
        <td><%= link_to 'Voir', automobile %></td>
        <td><%= link_to 'Vendre', edit_automobile_path(automobile) %></td>
        <td><%= link_to 'Supprimer', automobile, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
                        </div>
                        <div class="col-lg-6 col-12">
<p id="notice"><%= notice %></p>
<div class="card bg-danger text-white mb-4">
                                    <div class="card-body">
                                      <div>
  <h3>Automobiles vendues: <b><%=@vendus.count%></b></h3>
</div>

                                    </div>
                                    <div class="card-footer d-none align-items-center justify-content-between">
                                      <%= link_to "Bilan", statistics_path, class:"small text-white stretched-link" %>
                                        
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>

<div class="table-responsive mt-2">
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr class="bg-dark text-white text-center">
      <th>Marque</th>
      <th>Modele</th>
      <th>Prix</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @vendus.each do |automobile| %>
      <tr>
        <td><%= automobile.marque %></td>
        <td><%= automobile.modele %></td>
        <td><%= automobile.prix.to_i %></td>
        <td><%= link_to 'Voir', automobile %></td>
        <td><%= link_to 'Supprimer', automobile, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
                        </div>
                    </div>
                </main>
               <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; <b>OW Technology</b> 2020</div>
                         
                        </div>
                    </div>
                </footer>
            </div>
           
        </div>

app/views/automobiles/new.html.erb
 <%=render 'menus/top'%>
        <div id="layoutSidenav">
            <%=render 'menus/side'%>
                         <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
<h1>Ajouter une Automobile</h1>

<%= render 'form', automobile: @automobile %>

<%= link_to 'Retour', automobiles_path, class:"btn btn-danger" %>
</div>
</main>
</div>
</div>

app/views/automobiles/show.html.erb
        <%=render 'menus/top'%>
        <div id="layoutSidenav">
            <%=render 'menus/side'%>
                         <div id="layoutSidenav_content">
                <main>
                  <div class="container">
                    <div class="row">
                      <div class="col-lg-6 offset-lg-3">
                        <p id="notice"><%= notice %></p>


<div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header bg-primary text-white"><h3 class="text-center font-weight-light my-4">Automobile N° <%= @automobile.id %> </h3></div>
<p id="notice"><%= notice %></p>
<div class="card-body">
<p>
  <strong>Marque:</strong>
  <%= @automobile.marque %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @automobile.modele %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= @automobile.couleur %>
</p>

<p>
  <strong>Matricule:</strong>
  <%= @automobile.matricule %>
</p>

<h5>
  <strong>Prix:</strong>
  <b style="font-size: 24px;"><%= @automobile.prix %> XAF</b>
</h5>

<%= link_to 'Retour', automobiles_path %>
</div>
                                    
                                </div>
                      </div>
                    </div>
                  </div>
</main>
               <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; <b>OW Technology</b> 2020</div>
                         
                        </div>
                    </div>
                </footer>
            </div>
           
        </div>

app/views/automobiles/vendre.html.erb
<h1>Editing Automobile</h1>

<%= form_for @automobile do |form| %>
  <% if @automobile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(automobile.errors.count, "error") %> prohibited this automobile from being saved:</h2>

      <ul>
      <% automobile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="form-group col-6">
    <%= form.label :marque %>
    <%= form.text_field :marque, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :modèle %>
    <%= form.text_field :modele, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :couleur %>
    <%= form.text_field :couleur, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :matricule %>
    <%= form.text_field :matricule, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-6">
    <%= form.label :prix %>
    <%= form.text_field :price, class:"form-control", required: :true %>
  </div>

    <div class="form-group col-6">
    <%= form.label :etat %>
    <%= form.hidden_field :etat_id, class:"form-control", required: :true, value: 2 %>
  </div>

    <div class="form-group col-6">
    <%= form.label :entrée_le %>
    <%= form.datetime_select :billed_at, class:"form-control", required: :true %>
  </div>

  <div class="form-group col-12">
    <%= form.submit "Ajouter l'automobile", class:"btn btn-success" %>
  </div>
  </div>
<% end %>


<%= link_to 'Show', @automobile %> |
<%= link_to 'Back', automobiles_path %>